version: "3"

services:
  emily-image-classification-mxhem0:

    image: emily-image-classification-mxhem0
    container_name: emily-image-classification-mxhem0

    build:
      context: ../../
      dockerfile: ./Dockerfile

    env_file:
      - ./.env
    
    ports:
      - ${HOST_PORT}:${CONTAINER_PORT}

    ipc: ${IPC}
    runtime: ${RUNTIME}
    networks:
      - emily-image-classification-mxhem0-network

networks:
  emily-image-classification-mxhem0-network:
    driver: bridge
    name: emily-image-classification-mxhem0-network